batch_size: 64
class_weights:
- 1.5
- 4.0
- 1.5
dropout: 0.5
epochs: 50
features_path: ml/data/processed/BTCUSDT_5m_features.csv
gradient_clip: 1.0
hidden_dim: 128
labels_path: ml/data/processed/BTCUSDT_5m_labels.csv
lr: 0.0005
lr_factor: 0.5
lr_patience: 5
min_lr: 1.0e-05
num_layers: 2
save_path: ml/models/checkpoints/lstm_btcusdt.pth
seq_len: 60
val_split: 0.2
