batch_size: 64  # Reduced batch size for better generalization
class_weights:
- 1.5  # SELL
- 4.0  # HOLD (significantly increased weight)
- 1.5  # BUY
dropout: 0.5
epochs: 50  # Increased epochs
features_path: ml/data/processed/BTCUSDT_5m_features.csv
hidden_dim: 128
labels_path: ml/data/processed/BTCUSDT_5m_labels.csv
lr: 0.0005  # Reduced learning rate
num_layers: 2
save_path: ml/models/checkpoints/lstm_btcusdt.pth
seq_len: 60
val_split: 0.2
# Training parameters
gradient_clip: 1.0
lr_patience: 5
lr_factor: 0.5
min_lr: 0.00001
